"""Catálogo canónico de roles y permisos del MES V2."""

PERMISSION_SEED = (
    ('ot.view', 'Consultar órdenes de trabajo'),
    ('ot.create', 'Crear órdenes de trabajo'),
    ('ot.edit', 'Editar órdenes de trabajo'),
    ('ot.archive', 'Archivar órdenes de trabajo'),
    ('production.view', 'Consultar producción'),
    ('production.summary.view', 'Consultar resumen de producción'),
    ('production.edit', 'Registrar avances de producción'),
    ('production.process.edit', 'Configurar procesos y rutas'),
    ('production.personnel.assign', 'Asignar personal de producción'),
    ('production.incident.create', 'Registrar incidencias de producción'),
    ('production.progress.view', 'Consultar avance operativo de producción'),
    ('messages.view', 'Consultar mensajes de órdenes de trabajo'),
    ('messages.write', 'Registrar mensajes de órdenes de trabajo'),
    ('planning.view', 'Consultar planeamiento'),
    ('planning.edit', 'Editar planeamiento'),
    ('planning.schedule.edit', 'Editar programación'),
    ('warehouse.view', 'Consultar almacén'),
    ('warehouse.movements.create', 'Registrar movimientos de almacén'),
    ('warehouse.kardex.view', 'Consultar Kardex'),
    ('warehouse.adjust', 'Ajustar existencias de almacén'),
    ('logistics.view', 'Consultar logística'),
    ('logistics.dispatch.create', 'Crear despachos'),
    ('logistics.dispatch.edit', 'Editar despachos'),
    ('quality.view', 'Consultar calidad'),
    ('quality.inspect', 'Registrar inspecciones'),
    ('quality.release', 'Liberar elementos'),
    ('quality.documents.upload', 'Subir documentos de calidad'),
    ('documents.view', 'Consultar documentos'),
    ('documents.upload', 'Subir documentos'),
    ('documents.publish', 'Publicar documentos'),
    ('photos.view', 'Consultar fotografías'),
    ('photos.upload', 'Subir fotografías'),
    ('photos.publish', 'Publicar fotografías'),
    ('reports.view', 'Consultar reportes'),
    ('reports.generate', 'Generar reportes'),
    ('reports.export', 'Exportar reportes'),
    ('client_portal.create', 'Crear enlaces de portal cliente'),
    ('client_portal.publish', 'Publicar en portal cliente'),
    ('client_portal.revoke', 'Revocar enlaces de portal cliente'),
    ('users.manage', 'Gestionar usuarios'),
    ('roles.manage', 'Gestionar roles'),
    ('permissions.manage', 'Gestionar permisos'),
    ('settings.manage', 'Gestionar configuración técnica'),
    ('audit.view', 'Consultar auditoría'),
)

ROLE_SEED = (
    ('administrador_sistema', 'Administrador del sistema', (
        'users.manage', 'roles.manage', 'permissions.manage',
        'settings.manage', 'audit.view',
    )),
    ('produccion_oficina', 'Producción Oficina', (
        'ot.view', 'ot.create', 'ot.edit', 'ot.archive',
        'production.view', 'production.summary.view', 'production.edit',
        'production.process.edit', 'production.personnel.assign',
        'production.incident.create', 'production.progress.view',
        'messages.view', 'messages.write',
        'warehouse.view', 'documents.view', 'documents.upload',
        'documents.publish', 'photos.view', 'photos.upload', 'photos.publish',
        'reports.view', 'reports.generate', 'reports.export',
    )),
    ('produccion_planta', 'Producción Planta', (
        'ot.view', 'production.view', 'production.summary.view',
        'production.progress.view', 'messages.view',
        'documents.view', 'photos.view', 'reports.view',
    )),
    ('planeamiento', 'Planeamiento', (
        'ot.view', 'production.view', 'production.summary.view',
        'production.progress.view', 'messages.view',
        'planning.view', 'planning.edit', 'planning.schedule.edit',
        'reports.view', 'reports.export',
    )),
    ('almacen', 'Almacén', (
        'ot.view', 'production.summary.view', 'warehouse.view',
        'messages.view', 'messages.write',
        'warehouse.movements.create', 'warehouse.kardex.view',
        'warehouse.adjust', 'reports.view', 'reports.export',
    )),
    ('logistica', 'Logística', (
        'ot.view', 'production.summary.view', 'warehouse.view',
        'messages.view',
        'logistics.view', 'logistics.dispatch.create',
        'logistics.dispatch.edit', 'documents.view', 'documents.upload',
        'reports.view', 'reports.export',
    )),
    ('calidad', 'Calidad', (
        'ot.view', 'production.view', 'production.summary.view',
        'production.progress.view', 'messages.view',
        'quality.view', 'quality.inspect', 'quality.release',
        'quality.documents.upload', 'documents.view', 'documents.upload',
        'photos.view', 'photos.upload', 'reports.view', 'reports.export',
    )),
    ('comercial', 'Comercial', (
        'ot.view', 'production.summary.view', 'documents.view',
        'photos.view', 'messages.view', 'reports.view', 'reports.export',
    )),
    ('gerencia', 'Gerencia', (
        'ot.view', 'production.summary.view', 'planning.view',
        'production.progress.view', 'messages.view',
        'warehouse.view', 'logistics.view', 'quality.view',
        'documents.view', 'photos.view', 'reports.view', 'reports.export',
    )),
    ('administracion', 'Administración', (
        'ot.view', 'production.summary.view', 'planning.view',
        'messages.view',
        'warehouse.view', 'logistics.view', 'documents.view',
        'reports.view', 'reports.export',
    )),
)

ROLE_KEYS = frozenset(role[0] for role in ROLE_SEED)
